"""Generator agent: calls Groq LLM to generate final answer with citations."""

import logging
import os
import re
from typing import List, Dict

logger = logging.getLogger(__name__)


class Generator:
    def __init__(self, api_key: str | None = None):
        self.api_key = api_key or os.getenv("GROQ_API_KEY")
        self.gemini_api_key = os.getenv("GEMINI_API_KEY")

    def generate(self, query: str, context_docs: List[Dict], model: str = 'meta-llama-8b', memory=None, web_results=None) -> str:
        logger.info("Generating answer for query: %s", query)
        # If ChromaDB returned zero documents, inform the user explicitly.
        # All other cases should attempt generation (LLM or extractive) so
        # follow-up questions are never blocked by heuristics.
        if not context_docs:
            logger.warning("No context documents returned from ChromaDB for query: %s", query)
            return "Document content not found please upload again"
        prompt = self._build_prompt(query, context_docs, memory=memory, web_results=web_results)
        print("[groq] context_docs:", context_docs)
        print("[groq] prompt preview:", prompt[:1000])
        if self.api_key:
            logger.info("Sending to Groq with model %s", model)
            groq_answer = self._call_groq(prompt, model=model)
            if groq_answer:
                groq_answer = self._strip_numeric_citations(groq_answer)
                logger.info("Answer generated by Groq")
                return groq_answer
            logger.warning("Groq API unavailable or failed, trying Gemini fallback")

        if self.gemini_api_key:
            gemini_answer = self._call_gemini(prompt)
            if gemini_answer:
                gemini_answer = self._strip_numeric_citations(gemini_answer)
                logger.info("Answer generated by Gemini fallback")
                return gemini_answer

        # If LLM providers failed but we have document context or memory,
        # return an extractive snippet from the documents so the user always
        # receives an answer when ChromaDB had results.
        if context_docs or memory:
            try:
                extractive = self._extractive_fallback_answer(query, context_docs, memory)
                extractive = self._strip_numeric_citations(extractive)
                if extractive:
                    logger.info("Returning extractive fallback answer from documents")
                    return extractive
            except Exception:
                logger.exception("Extractive fallback failed")

        # If we reach here, return an empty string to avoid returning 'sorry'
        # for cases where documents were present but no LLM and no extractive
        # snippet could be produced. Upstream callers should still receive an
        # answer (possibly empty) but the only explicit 'Sorry' case is when
        # ChromaDB returned zero results (handled above).
        return ""

    def _extractive_fallback_answer(self, query: str, context_docs: List[Dict], memory=None) -> str:
        """Simple extractive fallback: find sentences in documents that match
        query keywords and return a concise plain-text answer."""
        if not context_docs:
            return ""

        q_terms = [t.lower() for t in re.findall(r"\w+", query) if len(t) > 2]
        results = []
        for doc in context_docs:
            text = doc.get("text", "")
            # Split into sentences conservatively
            sentences = re.split(r"(?<=[.!?])\s+", text)
            for s in sentences:
                s_l = s.lower()
                # prefer sentences that contain multiple query terms
                score = sum(1 for t in q_terms if t in s_l)
                if score > 0:
                    results.append((score, s.strip()))

        # fallback to whole doc snippet if no sentence matched
        if not results:
            combined = "\n\n".join(d.get("text", "") for d in context_docs[:3])
            # return first 400 chars to keep it concise
            return combined.strip()[:1000]

        # sort by score desc and return top sentences joined
        results.sort(key=lambda x: x[0], reverse=True)
        top = [s for _, s in results[:4]]
        answer = " ".join(top)
        # truncate to reasonable length
        return answer.strip()[:1000]

    def _call_groq(self, prompt: str, model: str = 'meta-llama-8b') -> str | None:
        try:
            logger.info("Calling Groq API with model %s", model)
            from groq import Groq
            client = Groq(api_key=self.api_key)
            system_prompt = (
                "Answer ONLY using the context below. Do not use your own knowledge. "
                "Do not make up anything. Only use exact information from the context provided."
            )
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt},
                ],
                max_tokens=1024,
                temperature=0.2,
            )
            answer = response.choices[0].message.content.strip()
            logger.info("Groq response received")
            return answer
        except Exception as exc:
            logger.exception("Groq generation failed: %s", exc)
            error_text = str(exc).lower()
            if 'decommissioned' in error_text or 'invalid_request_error' in error_text:
                if model != 'meta-llama-8b':
                    logger.warning("Retrying Groq with fallback model meta-llama-8b")
                    return self._call_groq(prompt, model='meta-llama-8b')
            return None

    def _call_gemini(self, prompt: str) -> str | None:
        client = None
        try:
            from google import genai
            from google.genai import types

            client = genai.Client(api_key=self.gemini_api_key)
            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt,
                config=types.GenerateContentConfig(
                    temperature=0.2,
                    max_output_tokens=1024,
                ),
            )
            return getattr(response, "text", None) or str(response)
        except Exception:
            logger.exception("Gemini fallback generation failed")
            try:
                import google.generativeai as genai
                genai.configure(api_key=self.gemini_api_key)
                response = genai.generate_text(
                    model="models/text-bison-001",
                    input=prompt,
                    temperature=0.2,
                    max_output_tokens=1024,
                )
                return getattr(response, "output", None) or getattr(response, "text", None) or str(response)
            except Exception:
                logger.exception("Legacy Gemini generation fallback failed")
                return None
        finally:
            if client is not None:
                try:
                    client.close()
                except Exception:
                    pass

    def _is_off_topic(self, answer: str, context_docs: List[Dict], query: str) -> bool:
        """Detect if answer appears to be hallucinated/off-topic compared to documents."""
        # Relevance/off-topic detection removed per project policy: always
        # forward answers from the LLM without blocking based on heuristics.
        return False

    def _strip_numeric_citations(self, text: str) -> str:
        """Remove all bracketed citation markers from answers.
        Citations are still returned separately in the API response `citations`/`sources`.
        """
        if not text:
            return text
        # Remove ANY brackets containing digits, 'source', or 'ref' - most aggressive approach
        # This matches [1], [1, 2, 3], [Source 1], [Source 1, Source 2], [1-3], etc.
        sanitized = re.sub(r"\[[^\]]*(?:\d+|source|ref)[^\]]*\]", "", text, flags=re.IGNORECASE)
        # Remove any standalone brackets with just numbers
        sanitized = re.sub(r"\[\s*\d+\s*\]", "", sanitized)
        # Remove text like "(Source: ...)" or "(Ref: ...)"
        sanitized = re.sub(r"\(\s*(?:source|ref|citation)s?[^)]*\)", "", sanitized, flags=re.IGNORECASE)
        # Collapse multiple spaces and fix spacing before punctuation
        sanitized = re.sub(r"\s+([.,;:!?])", r"\1", sanitized)
        sanitized = re.sub(r"\s{2,}", " ", sanitized).strip()
        return sanitized

    def _build_prompt(self, query: str, context_docs: List[Dict], memory=None, web_results=None) -> str:
        snippets = []
        for idx, doc in enumerate(context_docs[:6], start=1):
            metadata = doc.get("metadata", {})
            source = metadata.get("source") or metadata.get("title") or f"Document {idx}"
            page = metadata.get("page")
            page_label = f" (page {page})" if page else ""
            snippets.append(f"Document: {source}{page_label}\n{doc.get('text', '')}\n")

        memory_snippets = []
        if memory is not None:
            for turn in memory[-5:]:
                if "question" in turn and "answer" in turn:
                    memory_snippets.append(f"User: {turn['question']}\nAssistant: {turn['answer']}\n")
                elif "user" in turn and "bot" in turn:
                    memory_snippets.append(f"User: {turn['user']}\nAssistant: {turn['bot']}\n")

        search_snippets = []
        if web_results:
            for idx, result in enumerate(web_results[:3], start=1):
                title = result.get("title") or result.get("url")
                snippet = result.get("snippet") or result.get("description") or ""
                search_snippets.append(f"[{idx}] {title}: {snippet}")

        prompt_parts = [
            "Document context:",
        ]
        prompt_parts.extend(snippets)
        if memory_snippets:
            prompt_parts.append("\nConversation history:")
            prompt_parts.extend(memory_snippets)
        if search_snippets:
            prompt_parts.append("\nExternal web results (use only if explicitly requested):")
            prompt_parts.extend(search_snippets)
        prompt_parts.append(f"\nQuestion: {query}\nAnswer:")

        return "\n".join(prompt_parts)

    def _fallback_answer(self, prompt: str) -> str:
        # Deprecated fallback - keep as empty string to avoid accidental
        # 'sorry' responses from internal callers. The explicit Chroma-empty
        # message is handled in `generate()` above.
        return ""
